#!/usr/bin/env python3
"""
Shared helpers for loading KernelBench-style problems and kernels.

Used by benchmark.py and by the NCU wrapper script generated by
profile_ncu.py. Requires torch (runtime dependency on the GPU machine),
no other packages.

Contracts:
    problem.py — defines Model(nn.Module), get_inputs(), optional get_init_inputs()
    kernel.py  — defines kernel_function(*tensors) -> tensor(s)
"""

from __future__ import annotations

import importlib.util
import inspect
from pathlib import Path

import torch

DTYPE_NAMES = ("bfloat16", "float16", "float32")


def import_module_from_path(name: str, path: str | Path):
    path = Path(path)
    spec = importlib.util.spec_from_file_location(name, str(path))
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot import {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def load_problem(problem_path: str | Path):
    """Return (Model, get_inputs, get_init_inputs|None) from a problem file."""
    mod = import_module_from_path("problem", problem_path)
    return mod.Model, mod.get_inputs, getattr(mod, "get_init_inputs", None)


def detect_dtype(kernel_source: str, default: str = "bfloat16") -> torch.dtype:
    """Infer working dtype from dtype names mentioned in the kernel source."""
    for name in DTYPE_NAMES:
        if name in kernel_source:
            return getattr(torch, name)
    return getattr(torch, default)


def prepare_inputs(inputs, device: str = "cuda", dtype: torch.dtype = torch.bfloat16):
    """Move tensors to the device; cast floating-point tensors to dtype."""
    prepared = []
    for x in inputs:
        if isinstance(x, torch.Tensor):
            x = x.to(device)
            if x.is_floating_point():
                x = x.to(dtype)
        prepared.append(x)
    return prepared


def build_model(Model, get_init_inputs, device: str, dtype: torch.dtype):
    init_inputs = get_init_inputs() if get_init_inputs else []
    model = Model(*init_inputs).to(device)
    if dtype in (torch.bfloat16, torch.float16):
        model = model.to(dtype)
    model.eval()
    return model


def extract_model_params(model) -> list[torch.Tensor]:
    """Ordered weight/bias tensors from the model's modules (for kernels that
    take model parameters as extra positional arguments)."""
    params: list[torch.Tensor] = []
    seen: set[int] = set()
    for module in model.modules():
        for attr in ("weight", "bias"):
            p = getattr(module, attr, None)
            if isinstance(p, torch.Tensor) and id(p) not in seen:
                seen.add(id(p))
                params.append(p.detach())
    return params


def prepare_kernel_callable(kernel_path: str | Path, inputs, model=None):
    """Load kernel_function and return (fn, args).

    If the kernel signature takes more positional parameters than the problem
    inputs (or is *args), append the model's weight/bias tensors in module
    order — this covers kernels that fold nn.Module parameters into their
    argument list.
    """
    mod = import_module_from_path("kernel", kernel_path)
    fn = mod.kernel_function

    args = list(inputs)
    n_positional = None
    has_varargs = False
    try:
        sig = inspect.signature(fn)
        n_positional = sum(
            1
            for p in sig.parameters.values()
            if p.kind in (p.POSITIONAL_ONLY, p.POSITIONAL_OR_KEYWORD)
            and p.default is p.empty
        )
        has_varargs = any(
            p.kind == p.VAR_POSITIONAL for p in sig.parameters.values()
        )
    except (TypeError, ValueError):
        pass

    if model is not None and n_positional is not None and n_positional > len(args):
        extra = extract_model_params(model)
        needed = n_positional - len(args)
        args = args + extra[:needed]
    elif model is not None and has_varargs and n_positional == len(args):
        pass  # exact match; varargs unused

    return fn, args
